$ipc = noctalia-shell ipc call

source = ./launchers.conf
source = ./media.conf
source = ./windows.conf

# Core binds
# bind = SUPER, S, exec, $ipc controlCenter toggle
# bind = SUPER, comma, exec, $ipc settings toggle

# bind = SUPER, V, exec, dms ipc call clipboard toggle
# bind = SUPER, M, exec, dms ipc call processlist focusOrToggle
# bind = SUPER, comma, exec, dms ipc call settings focusOrToggle
# bind = SUPER, N, exec, dms ipc call notifications toggle
# bind = SUPER SHIFT, N, exec, dms ipc call notepad toggle
# bind = SUPER, Y, exec, dms ipc call dankdash wallpaper
# bind = SUPER, TAB, exec, dms ipc call hypr toggleOverview
# bind = SUPER, X, exec, dms ipc call powermenu toggle

# === Security ===
bind = SUPER, L, exec, $ipc lockScreen lock
# bind = SUPER SHIFT, E, exit
# bind = CTRL ALT, Delete, exec, dms ipc call processlist focusOrToggle

# === Window Management ===
bind = SUPER, Q, killactive
bind = SUPER, F, fullscreen, 1
bind = SUPER SHIFT, F, fullscreen, 0
bind = SUPER SHIFT, T, togglefloating
bind = SUPER, W, togglegroup
# bind = SUPER SHIFT, W, exec, dms ipc call window-rules toggle

# === Screenshots ===
# bind = , Print, exec, dms screenshot
# bind = CTRL, Print, exec, dms screenshot full
# bind = ALT, Print, exec, dms screenshot window

# === System Controls ===
# bind = SUPER SHIFT, P, dpms, toggle
