bind = SUPER, space, exec, $ipc launcher toggle
bind = SUPER SHIFT, slash, exec, $ipc plugin:keybind-cheatsheet toggle
bind = SUPER, tab, exec, $ipc plugin:workspace-overview toggle

bind = SUPER, return, exec, kitty
bind = SUPER, B, exec, firefox
bind = SUPER, E, exec, dolphin
