# === Audio Controls ===
bindel = , XF86AudioRaiseVolume, exec, $ipc volume increase
bindel = , XF86AudioLowerVolume, exec, $ipc volume decrease
bindl = , XF86AudioMute, exec, $ipc volume muteOutput
bindl = , XF86AudioMicMute, exec, $ipc volume muteInput
bindl = , XF86AudioPlay, exec, $ipc media playPause
bindl = , XF86AudioPrev, exec, $ipc media previous
bindl = , XF86AudioNext, exec, $ipc media next

# === Brightness Controls ===
bindel = , XF86MonBrightnessUp, exec, $ipc brightness increase
bindel = , XF86MonBrightnessDown, exec, $ipc brightness decrease
