# === Audio Controls ===
# bindel = , XF86AudioRaiseVolume, exec, dms ipc call audio increment 3
# bindel = , XF86AudioLowerVolume, exec, dms ipc call audio decrement 3
# bindl = , XF86AudioMute, exec, dms ipc call audio mute
# bindl = , XF86AudioMicMute, exec, dms ipc call audio micmute
# bindl = , XF86AudioPause, exec, dms ipc call mpris playPause
# bindl = , XF86AudioPlay, exec, dms ipc call mpris playPause
# bindl = , XF86AudioPrev, exec, dms ipc call mpris previous
# bindl = , XF86AudioNext, exec, dms ipc call mpris next
# bindel = CTRL, XF86AudioRaiseVolume, exec, dms ipc call mpris increment 3
# bindel = CTRL, XF86AudioLowerVolume, exec, dms ipc call mpris decrement 3
bindel = , XF86AudioRaiseVolume, exec, $ipc volume increase
bindel = , XF86AudioLowerVolume, exec, $ipc volume decrease
bindl = , XF86AudioMute, exec, $ipc volume muteOutput

# === Brightness Controls ===
# bindel = , XF86MonBrightnessUp, exec, dms ipc call brightness increment 5 ""
# bindel = , XF86MonBrightnessDown, exec, dms ipc call brightness decrement 5 ""
bindel = , XF86MonBrightnessUp, exec, $ipc brightness increase
bindel = , XF86MonBrightnessDown, exec, $ipc brightness decrease
