monitorv2 {
    output = DP-1
    mode = preferred
    position = auto
    scale = 1
}
monitorv2 {
    output = DP-2
    mode = preferred
    position = auto
    scale = 1
}
monitorv2 {
    output = 
    mode = preferred
    position = auto
    scale = 1
}

workspace = 1, persistent:true, monitor:DP-1, default:true
workspace = 2, persistent:true, monitor:DP-1
workspace = 3, persistent:true, monitor:DP-1
workspace = 4, persistent:true, monitor:DP-1
workspace = 5, persistent:true, monitor:DP-1
workspace = 6, persistent:true, monitor:DP-1
workspace = 7, persistent:true, monitor:DP-2, default:true
workspace = 8, persistent:true, monitor:DP-2
workspace = 9, persistent:true, monitor:DP-2
workspace = 10, persistent:true, monitor:DP-2
workspace = 11, persistent:true, monitor:DP-2
workspace = 12, persistent:true, monitor:DP-2
