monitor = , preferred, auto, 1.25

workspace = 1, persistent:true, default:true
workspace = 2, persistent:true
workspace = 3, persistent:true
workspace = 4, persistent:true
workspace = 5, persistent:true
workspace = 6, persistent:true

input {
    touchpad {
        clickfinger_behavior = 1
        natural_scroll = true
    }
}

gestures {
    gesture = 3, horizontal, workspace
    gesture = 3, up, dispatcher, exec, $ipc plugin:workspace-overview toggle
    workspace_swipe_min_speed_to_force = 15
    workspace_swipe_cancel_ratio = 0.35
}
