monitor = , preferred, auto, 1.25

workspace = 1, persistent:true, default:true
workspace = 2, persistent:true
workspace = 3, persistent:true
workspace = 4, persistent:true
workspace = 5, persistent:true
workspace = 6, persistent:true

input {
    touchpad {
        clickfinger_behavior = 1
        natural_scroll = true
    }
}
