{
  imports = [
    ../features/cli.nix
    ../features/desktop.nix
    ../features/discord.nix
    ../features/fastfetch.nix
    ../features/firefox
    ../features/fonts.nix
    ../features/gaming.nix
    ../features/git.nix
    ../features/home-manager.nix
    ../features/hyprland.nix
    ../features/kitty.nix
    ../features/noctalia.nix
    ../features/stylix.nix
    ../features/vscode.nix
    ../features/zsh.nix
  ];
}